# Generated by Django 3.2.5 on 2021-11-01 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jounral',
            new_name='Journal',
        ),
    ]
