# Generated by Django 3.2.5 on 2021-10-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='agency',
            field=models.TextField(default='hi', max_length=10000),
        ),
        migrations.AddField(
            model_name='award',
            name='award',
            field=models.TextField(default='hi', max_length=10000),
        ),
        migrations.AddField(
            model_name='award',
            name='name',
            field=models.TextField(default='hi', max_length=10000),
        ),
        migrations.AddField(
            model_name='book',
            name='book_chap',
            field=models.TextField(default='hi', max_length=10000),
        ),
        migrations.AddField(
            model_name='book',
            name='book_title',
            field=models.TextField(default='hi', max_length=10000),
        ),
        migrations.AddField(
            model_name='book',
            name='chap_title',
            field=models.TextField(default='hi', max_length=10000),
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.TextField(default='hi', max_length=10000),
        ),
        migrations.AddField(
            model_name='grant',
            name='agency',
            field=models.TextField(default='hi', max_length=10000),
        ),
        migrations.AddField(
            model_name='grant',
            name='pi',
            field=models.TextField(default='hi', max_length=10000),
        ),
        migrations.AddField(
            model_name='grant',
            name='title',
            field=models.TextField(default='hi', max_length=10000),
        ),
        migrations.AddField(
            model_name='jounral',
            name='name',
            field=models.TextField(default='hi', max_length=10000),
        ),
        migrations.AddField(
            model_name='jounral',
            name='title',
            field=models.TextField(default='hi', max_length=10000),
        ),
        migrations.AddField(
            model_name='patent',
            name='agency',
            field=models.TextField(default='hi', max_length=10000),
        ),
        migrations.AddField(
            model_name='patent',
            name='title',
            field=models.TextField(default='hi', max_length=10000),
        ),
    ]
