# Generated by Django 3.2.5 on 2021-11-01 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerps', '0002_rename_jounral_journal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_chap',
        ),
        migrations.AddField(
            model_name='book',
            name='book_bool',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='grant',
            name='budget',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grant',
            name='duaration_from',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grant',
            name='duration_to',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='book',
            name='chap_title',
            field=models.TextField(max_length=10000),
        ),
    ]
