# Generated by Django 3.2.5 on 2021-10-23 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerps', '0002_auto_20211023_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='', max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='award',
            name='year',
            field=models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(2999)]),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='book',
            name='year',
            field=models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(2999)]),
        ),
        migrations.AddField(
            model_name='jounral',
            name='issue',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='jounral',
            name='pages',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='jounral',
            name='volume',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='patent',
            name='number',
            field=models.IntegerField(default=''),
        ),
        migrations.AddField(
            model_name='patent',
            name='year',
            field=models.IntegerField(default='', validators=[django.core.validators.MaxValueValidator(2999)]),
        ),
        migrations.AlterField(
            model_name='award',
            name='agency',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='award',
            name='award',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='award',
            name='name',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_chap',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_title',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='book',
            name='chap_title',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='grant',
            name='agency',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='grant',
            name='pi',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='grant',
            name='title',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='jounral',
            name='name',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='jounral',
            name='title',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='patent',
            name='agency',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='patent',
            name='title',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='book', to='cerps.People'),
        ),
        migrations.AddField(
            model_name='grant',
            name='co_investigators',
            field=models.ManyToManyField(related_name='grant', to='cerps.People'),
        ),
        migrations.AddField(
            model_name='jounral',
            name='authors',
            field=models.ManyToManyField(related_name='journal', to='cerps.People'),
        ),
        migrations.AddField(
            model_name='patent',
            name='authors',
            field=models.ManyToManyField(related_name='patent', to='cerps.People'),
        ),
    ]
