# Generated by Django 3.2.5 on 2021-11-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerps', '0003_auto_20211101_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='duaration_from',
            field=models.DateField(default=0),
        ),
        migrations.AlterField(
            model_name='grant',
            name='duration_to',
            field=models.DateField(default=0),
        ),
    ]
