# Generated by Django 3.2.5 on 2021-11-03 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerps', '0004_auto_20211101_2112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='chap_title',
            new_name='chapter_title',
        ),
    ]
