# Generated by Django 3.2.5 on 2021-10-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerps', '0004_auto_20211023_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jounral',
            name='issue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jounral',
            name='pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='jounral',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
