# Generated by Django 3.2.5 on 2021-11-03 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerps', '0005_rename_chap_title_book_chapter_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='grant',
            old_name='duaration_from',
            new_name='duration_from',
        ),
    ]
