# Generated by Django 3.2.5 on 2021-10-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerps', '0005_auto_20211023_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='patent',
            name='year',
            field=models.IntegerField(default=0),
        ),
    ]
