# Generated by Django 3.2.5 on 2021-10-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cerps', '0006_auto_20211023_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='year',
        ),
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
        migrations.RemoveField(
            model_name='patent',
            name='year',
        ),
    ]
