# Generated by Django 3.2.5 on 2022-01-05 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cerps', '0006_rename_duaration_from_grant_duration_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='pages',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
